# Generated by Django 3.0.1 on 2019-12-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='Actors',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='rank',
            new_name='Metascrore',
        ),
        migrations.AddField(
            model_name='movie',
            name='Description',
            field=models.CharField(default=1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='Genre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='Rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='Rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='Revenue',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='Runtime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='Title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='Votes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='Year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
