# Generated by Django 3.0.1 on 2019-12-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20191228_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Metascrore',
            new_name='Metascore',
        ),
    ]
