# Generated by Django 3.0.1 on 2019-12-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20191228_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Rank',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
