# Generated by Django 3.0.1 on 2019-12-29 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0007_moviecart_movieorder_movieorderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movieorder',
            name='order_number',
            field=models.CharField(default='QNPHDAKLBB', max_length=12),
        ),
        migrations.AlterField(
            model_name='movieorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movieorderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='cart.MovieOrder'),
        ),
    ]
